name: 'mwg-check'

on:
  pull_request:
          #types: [opened, reopened, edited, synchronize]
    paths:
      - 'ansible/**'
        #  pull_request_review:
        #    types: [dismissed]

permissions:
  contents: read
  pull-requests: write

jobs:
  check:
    if: ${{ (!github.event.pull_request.merged ) && (!github.event.pull_request.draft) && (needs.check.outputs.run_job == 'true') }}
    runs-on: [ self-hosted, Linux ]
    defaults:
      run:
        working-directory: ./ansible
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      with:
        filters: '.github/filters.yaml'
    - uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}
    - id: 'mwg-check'
      run: |
        ansible-playbook -i inventory.yaml hello-world.yaml -C
